version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:3001/api/v1
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - firestore

  firestore:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    command: >
      sh -c "gcloud emulators firestore start --host-port=0.0.0.0:8080 --project=demo-project"
    ports:
      - "8080:8080"
    environment:
      - FIRESTORE_EMULATOR_HOST=localhost:8080

volumes:
  node_modules_frontend:
  node_modules_backend:
